/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.prithvis.musicbob;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
import org.telegram.telegrambots.updatesreceivers.DefaultBotSession;

public class App {
    private static final Logger LOGGER = LogManager.getLogger(App.class);
    public static void main(String[] args) throws TelegramApiException {
        TelegramBotsApi botsApi = new TelegramBotsApi(DefaultBotSession.class);
        if(args.length!=2){
            LOGGER.error("Requires botToken and botUserName");
        }
        botsApi.registerBot(new MusicBobBot(args[0], args[1]));
    }
}
